spring.application.name=spring-ai-chat
spring.ai.google.genai.api-key=YOUR_GEMINI_API_KEY
#spring.ai.google.genai.api-key=YOUR_API_KEY
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview
server.port=8081
